2024-05-03 04:00:56,919 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-05-03 04:00:56,919 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Configure stats pid to 1144974
2024-05-03 04:00:56,919 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from /home/user126/.config/wandb/settings
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from /home/user126/TFformer/model/wandb/settings
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'model/TFformer.py', 'program_abspath': '/home/user126/TFformer/model/TFformer.py', 'program': '/home/user126/TFformer/model/TFformer.py'}
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_init.py:_log_setup():524] Logging user logs to /home/user126/TFformer/model/wandb/run-20240503_040056-79dragzy/logs/debug.log
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_init.py:_log_setup():525] Logging internal logs to /home/user126/TFformer/model/wandb/run-20240503_040056-79dragzy/logs/debug-internal.log
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_init.py:init():564] calling init triggers
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-05-03 04:00:56,920 INFO    MainThread:1144974 [wandb_init.py:init():589] re-initializing run, found existing run on stack: v5q3ec2b
2024-05-03 04:00:56,922 INFO    MainThread:1144974 [wandb_run.py:_finish():1962] finishing run best_/TFformer-model/v5q3ec2b
2024-05-03 04:00:56,922 ERROR   MainThread:1144974 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-05-03 04:00:56,922 INFO    MainThread:1144974 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-05-03 04:00:56,922 INFO    MainThread:1144974 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-05-03 04:00:56,922 INFO    MainThread:1144974 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-05-03 04:00:56,922 INFO    MainThread:1144974 [wandb_run.py:_restore():2185] restore
2024-05-03 04:00:56,923 INFO    MainThread:1144974 [wandb_run.py:_restore():2191] restore done
2024-05-03 04:01:01,432 INFO    MainThread:1144974 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-05-03 04:01:01,432 INFO    MainThread:1144974 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-05-03 04:01:01,436 INFO    MainThread:1144974 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-05-03 04:01:01,538 INFO    MainThread:1144974 [wandb_init.py:init():614] starting backend
2024-05-03 04:01:01,538 INFO    MainThread:1144974 [wandb_init.py:init():618] setting up manager
2024-05-03 04:01:01,540 INFO    MainThread:1144974 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-03 04:01:01,540 INFO    MainThread:1144974 [wandb_init.py:init():624] backend started and connected
2024-05-03 04:01:01,544 INFO    MainThread:1144974 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-05-03 04:01:01,544 INFO    MainThread:1144974 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-03 04:01:01,544 INFO    MainThread:1144974 [wandb_init.py:init():716] updated telemetry
2024-05-03 04:01:01,552 INFO    MainThread:1144974 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-05-03 04:01:02,951 INFO    MainThread:1144974 [wandb_run.py:_on_init():2254] communicating current version
2024-05-03 04:01:03,035 INFO    MainThread:1144974 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-03 04:01:03,035 INFO    MainThread:1144974 [wandb_init.py:init():800] starting run threads in backend
2024-05-03 04:01:05,585 INFO    MainThread:1144974 [wandb_run.py:_console_start():2233] atexit reg
2024-05-03 04:01:05,585 INFO    MainThread:1144974 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-05-03 04:01:05,585 INFO    MainThread:1144974 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-05-03 04:01:05,585 INFO    MainThread:1144974 [wandb_run.py:_redirect():2178] Redirects installed.
2024-05-03 04:01:05,586 INFO    MainThread:1144974 [wandb_init.py:init():841] run started, returning control to user process
2024-05-03 04:01:05,689 INFO    MainThread:1144974 [wandb_run.py:_config_callback():1342] config_cb None None {'dim_treatments': 4, 'dim_covariates': 3, 'dim_outcomes': 4, 'dim_statics': None, 'seq_hidden_units': 32, 'iw': 70, 'ow': 21, 'num_heads': 2, 'dropout_rate': 0.2, 'num_layer': 3}
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Configure stats pid to 1144974
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from /home/user126/.config/wandb/settings
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from /home/user126/TFformer/model/wandb/settings
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'model/TFformer.py', 'program_abspath': '/home/user126/TFformer/model/TFformer.py', 'program': '/home/user126/TFformer/model/TFformer.py'}
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:_log_setup():524] Logging user logs to /home/user126/TFformer/model/wandb/run-20240503_040112-fzurz0f8/logs/debug.log
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:_log_setup():525] Logging internal logs to /home/user126/TFformer/model/wandb/run-20240503_040112-fzurz0f8/logs/debug-internal.log
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2524147fd0>
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:init():564] calling init triggers
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-05-03 04:01:12,957 INFO    MainThread:1144974 [wandb_init.py:init():589] re-initializing run, found existing run on stack: 79dragzy
2024-05-03 04:01:12,959 INFO    MainThread:1144974 [wandb_run.py:_finish():1962] finishing run best_/TFformer-model/79dragzy
2024-05-03 04:01:12,960 INFO    MainThread:1144974 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-05-03 04:01:12,960 INFO    MainThread:1144974 [wandb_run.py:_restore():2185] restore
2024-05-03 04:01:12,960 INFO    MainThread:1144974 [wandb_run.py:_restore():2191] restore done
2024-05-03 04:01:17,925 INFO    MainThread:1144974 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-05-03 04:01:17,925 INFO    MainThread:1144974 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-05-03 04:01:17,929 INFO    MainThread:1144974 [wandb_run.py:_footer_sync_info():3796] logging synced files
